In [1]:
import numpy as sa
from numpy import *
arr=sa.array([1,2,35.7,4])
print(arr)

[ 1.   2.  35.7  4. ]


In [3]:
print(arr.dtype)

float64


In [5]:
arr= zeros([2,3,6],int)
print(arr.dtype)
print(arr)

int64
[[[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]]


In [17]:
arr= ones([2,4,6],int)
print(arr.dtype)
print(arr)

int64
[[[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]]


In [9]:
list=[1,3,4,5]
arr=sa.array(list)
print(arr)

[1 3 4 5]


In [10]:
list =[1,2,4,5],[5,6,7,8]
arr =sa.array(list)
print(arr)

[[1 2 4 5]
 [5 6 7 8]]


In [11]:
arr=sa.arange(1,20)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
arr=sa.arange(1,20,4)
print(arr)

[ 1  5  9 13 17]


In [30]:
arr=logspace(1,30,5)
print(arr)

[1.00000000e+01 1.77827941e+08 3.16227766e+15 5.62341325e+22
 1.00000000e+30]


In [32]:
print(arr[2])

3162277660168379.5


In [19]:
matrix = sa.full(5,6)
print(matrix)

[6 6 6 6 6]


In [22]:
matrix = sa.full((3,2),5)
print(matrix)

[[5 5]
 [5 5]
 [5 5]]


In [33]:
matrix= sa.eye(3)
print(matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
mat = sa.diag([1,3,4])
print(mat)

[[1 0 0]
 [0 3 0]
 [0 0 4]]


In [36]:
arr = sa.random.rand(6)
print(arr)

[0.33155834 0.32526093 0.19804766 0.77433983 0.36965516 0.0723654 ]


In [37]:
arr = sa.random.rand(6,5)
print(arr)

[[0.65610777 0.60968114 0.23527392 0.81283177 0.96959976]
 [0.41817931 0.99979287 0.83603963 0.97963213 0.11079221]
 [0.38436545 0.21771953 0.40344052 0.53978856 0.36105097]
 [0.94383917 0.64034736 0.66284669 0.70844157 0.79011125]
 [0.86780127 0.5605491  0.0514593  0.05034559 0.3215884 ]
 [0.48877396 0.22306071 0.48327706 0.07416828 0.26961371]]


In [41]:
arr = sa.random.randn(4,6,2)
print(arr)

[[[ 0.31416939 -0.73299364]
  [ 1.71899257  0.51011513]
  [-0.45710294  0.33201377]
  [ 0.10794231  0.33945057]
  [-0.03065015  1.66570626]
  [-0.7810775   1.22316411]]

 [[ 2.30697317 -1.23382307]
  [ 0.46551964  1.10746386]
  [ 0.85491201  1.12356118]
  [ 0.78837798  1.39350032]
  [-1.60919991 -0.66892219]
  [-0.89905047 -0.63730241]]

 [[-1.50110784  0.76408194]
  [ 1.30651707  0.32769465]
  [ 0.54009863  0.91304683]
  [-0.98090817 -1.28220758]
  [ 2.39425392  1.19612153]
  [-2.19825902  0.60883107]]

 [[-0.21641846 -0.12347693]
  [ 0.15255167 -1.06649573]
  [ 1.4084649  -0.46243866]
  [-0.90072246  0.14092524]
  [-1.45852675 -1.25962433]
  [-0.12104479  1.53214096]]]


In [42]:
arr = sa.random.randint(5,6,6)
print(arr)

[5 5 5 5 5 5]
